name: arctekko
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  get: ^3.21.1
  logger: ^0.9.4
  get_storage: ^1.3.2
  objectbox: ^0.11.0
  objectbox_flutter_libs: ^0.11.0
  darq: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.4
  json_serializable: ^3.5.0
  objectbox_generator: any

flutter:
  uses-material-design: true